/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoopsRouteImport } from './routes/loops'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopsRoute = LoopsRouteImport.update({
  id: '/loops',
  path: '/loops',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/decisions': typeof DecisionsRoute
  '/import': typeof ImportRoute
  '/loops': typeof LoopsRoute
  '/settings': typeof SettingsRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/decisions': typeof DecisionsRoute
  '/import': typeof ImportRoute
  '/loops': typeof LoopsRoute
  '/settings': typeof SettingsRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/agent': typeof AgentRoute
  '/decisions': typeof DecisionsRoute
  '/import': typeof ImportRoute
  '/loops': typeof LoopsRoute
  '/settings': typeof SettingsRoute
  '/projects/$id': typeof ProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/agent'
    | '/decisions'
    | '/import'
    | '/loops'
    | '/settings'
    | '/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/agent'
    | '/decisions'
    | '/import'
    | '/loops'
    | '/settings'
    | '/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/agent'
    | '/decisions'
    | '/import'
    | '/loops'
    | '/settings'
    | '/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AgentRoute: typeof AgentRoute
  DecisionsRoute: typeof DecisionsRoute
  ImportRoute: typeof ImportRoute
  LoopsRoute: typeof LoopsRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loops': {
      id: '/loops'
      path: '/loops'
      fullPath: '/loops'
      preLoaderRoute: typeof LoopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AgentRoute: AgentRoute,
  DecisionsRoute: DecisionsRoute,
  ImportRoute: ImportRoute,
  LoopsRoute: LoopsRoute,
  SettingsRoute: SettingsRoute,
  ProjectsIdRoute: ProjectsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
